Add files via upload

diff --git a/stop-wan-leak/09-stop-wan-leak b/stop-wan-leak/09-stop-wan-leak
--- a/stop-wan-leak/09-stop-wan-leak
+++ b/stop-wan-leak/09-stop-wan-leak
@@ -2,55 +2,79 @@
 #DEBUG=; set -x; logger -t stop-wan-leak $(env); # uncomment/comment to enable/disable debug mode
 
 # Name: 09-stop-wan-leak
-# Version: 0.93 5-nov-2025 by egc
-# Description: OpenWRT hoptlug script disabling forwarding to stop a wan leak while PBR is starting
-# Operating mode: The script is triggered by the WAN interface going up this can happen multiple times but after the WAN interface is up the critical period starts
+# Version: 0.94 14-feb-2026 by egc
+# Description: OpenWRT hoptlug script disabling forwarding to stop a wan leak while PBR is (re)starting
+# Operating mode: The script is triggered by the WAN interface or VPN interface going up
 # Usage: e.g. if you want to be sure there is no wan leak while using your VPN and PBR
 # Note this only takes care of forwarding so blocking your lan client from accessing the wan, the router itself can still access the wan
 # Installation:
 #  Copy script from https://raw.githubusercontent.com/egc112/OpenWRT-egc-add-on/main/stop-wan-leak/09-stop-wan-leak to your router either
 #     with, from commandline (SSH): curl -o /etc/hotplug.d/iface/09-stop-wan-leak https://raw.githubusercontent.com/egc112/OpenWRT-egc-add-on/main/stop-wan-leak/09-stop-wan-leak
 #     or by clicking the download icon in the upper right corner of the script and using e.g. winscp to transfer the script.
-#  Edit script and set MYWANIF to your current name of the wan interface as defined in /etc/config/network which by defualt is `wan`  
+#  Edit script and set MYWANIF to your current name of the wan interface as defined in /etc/config/network which by default is wan and set the name of your WireGuard interface
 #  Reboot or restart network (service network restart)
 # Check the working with `logread -e stop-wan-leak`
 # Enable debugging by removing the # before the #DEBUG= ... on line 2, check debug output with `logread -e stop-wan-leak`
+# To preserve the script between upgrades add to /etc/sysupgrade.conf: `/etc/hotplug.d/iface/09-stop-wan-leak`
 
-MYWANIF="wan"	# set the interface you are using as wan, check form command line with `ifconfig` or `ip address show`
+# https://forum.openwrt.org/t/pbr-wg-bootup-leak-bootup-killswitch-scripts/241991/7
 
-MAXSLEEP=60		# Maximum sleep time to prevent deadlock
-PBRSLEEP=5		# Extra sleep time after PBR is enabled to make sure PBR rules are functioning
+MYWANIF="wan"		# set the logical interface you are using as wan as shown in Networks > Interfaces
+MYVPNIF="wireguard"	# set the name of the VPN interface name as shown in Networks > Interfaces
+
+MAXSLEEP=90		# Maximum sleep time to prevent deadlock
+PBRSLEEP=20		# Extra sleep time after PBR is enabled to make sure PBR rules are functioning
 
 #==========DO NOT ALTER BELOW THIS LINE==================
 SLEEP=0
 {
-if [ "$INTERFACE" == "$MYWANIF" ] && [ "$ACTION" == "ifup" ]; then
-	echo "stop-wan-leak: disable forwarding on ifup of $MYWANIF"
-	/sbin/sysctl -w net.ipv4.ip_forward=0
-	/sbin/sysctl -w net.ipv6.conf.all.forwarding=0
+enable_forward() {
+	if [ "$(cat /proc/sys/net/ipv4/ip_forward)" != "1" ]; then
+		/sbin/sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1
+		/sbin/sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null 2>&1
+		echo "stop-wan-leak: Forwarding is enabled"
+	fi
+}
+stop_forward() {
+	if [ "$(cat /proc/sys/net/ipv4/ip_forward)" != "0" ]; then
+		/sbin/sysctl -w net.ipv4.ip_forward=0 >/dev/null 2>&1
+		/sbin/sysctl -w net.ipv6.conf.all.forwarding=0 >/dev/null 2>&1
+		echo "stop-wan-leak: Disable forwarding on ifup of $MYWANIF"
+	fi
+}
+
+is_enabled() { ls /etc/rc.d/*"${1}"* >/dev/null 2>&1; }
+
+#Determine wan device
+WANIF="$(uci -q get pbr.config.uplink_interface)"
+if [ -z "$WANIF" ]; then 
+	WANIF="$MYWANIF"
+	echo "stop-wan-leak: no uplink interface defined in PBR config, assuming the logical interface name of wan is $WANIF"
 fi
-while [ $SLEEP -le $MAXSLEEP ]; do
-	SLEEP=$((SLEEP + 1))
-	sleep 1
-	# if pbr is not enabled break
-	if ! ls /etc/rc.d/*pbr* >/dev/null 2>&1; then
-		echo "stop-wan-leak: pbr is not enabled so going to enable forwarding"
-		break
+
+if  { [ "$INTERFACE" == "$WANIF" ] || [ "$INTERFACE" == "$MYVPNIF" ]; } && [ "$ACTION" == "ifup" ]; then
+	stop_forward
+	while [ $SLEEP -le $MAXSLEEP ]; do
+		SLEEP=$((SLEEP + 1))
+		sleep 1
+		# if pbr is not enabled break
+		if ! is_enabled "pbr"; then
+			echo "stop-wan-leak: pbr is not enabled so going to enable forwarding"
+			break
+		fi
+		#if pbr is enabled and running then also enable forwarding
+		if ubus call service list '{"name":"pbr"}' | grep -q '"running": '; then
+			sleep $PBRSLEEP
+			#SLEEP=$((SLEEP + PBRSLEEP))
+			echo "stop-wan-leak: Forwarding disabled during $SLEEP + $PBRSLEEP =  $((SLEEP + PBRSLEEP)) sec. but is now enabled after PBR is running "
+			break
+		fi
+	done
+	if [ $SLEEP -gt $MAXSLEEP ]; then
+		echo "stop-wan-leak: ERROR: Forwarding is now enabled due to exceeding the maximum sleep time of $MAXSLEEP sec. wan leak possible !"
+		echo "stop-wan-leak: ERROR: Check that PBR is running"
 	fi
-	#if pbr is enabled and running then also enable forwarding
-	if ubus call service list '{"name":"pbr"}' | grep -q '"running": '; then
-	 sleep $PBRSLEEP
-	 SLEEP=$((SLEEP + 5))
-	 echo "stop-wan-leak: forwarding disabled during $SLEEP sec but is now enabled after PBR is running "
-	 break
-	fi
-done
-/sbin/sysctl -w net.ipv4.ip_forward=1
-/sbin/sysctl -w net.ipv6.conf.all.forwarding=1
-if [ $SLEEP -gt $MAXSLEEP ]; then
-	echo "stop-wan-leak: ERROR: forwarding is now enabled due to exceeding the maximum sleep time of $MAXSLEEP sec. wan leak possible !"
-else
-	echo "stop-wan-leak: forwarding is now enabled after $SLEEP sec."
+	enable_forward
 fi
 } 2>&1 | logger $([ ${DEBUG+x} ] && echo '-p user.debug') \
     -t $(echo $(basename $0) | grep -Eo '^.{0,23}')[$$] &
